//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidoresInteligentesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lectura
    {
        public int id { get; set; }
        public int medidorTipo { get; set; }
        public Nullable<System.DateTime> fechaLectura { get; set; }
        public string horaLectura { get; set; }
        public Nullable<decimal> valorConsumo { get; set; }
    
        public virtual Medidor Medidor { get; set; }
    }
}
